apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    app: multi-pod
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: httpd-container
    image: 
    volumeMounts:
    - name: 
      mountPath: 
  - name: alpine-container
    image: 
    volumeMounts:
    - name: 
      mountPath: 
    command: ["/bin/sh"]
    args: [ "-c", "echo hello world > /pod-data/index.html && sleep 3600" ]